spring:
  datasource:
    initialization-mode: always # always or never
    url: jdbc:mysql://localhost:3306/test_db?serverTimezone=JST
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: devdb

logging.level.org.springframework: debug
logging.level.com.example.demo: debug